// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_CodeFirst_bai1.Data;

namespace WebAPI_CodeFirst_bai1.Migrations
{
    [DbContext(typeof(HangHoaDBContext))]
    partial class HangHoaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI_CodeFirst_bai1.Models.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TinhTrangDonDatHang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("WebAPI_CodeFirst_bai1.Models.DonHangChiTiet", b =>
                {
                    b.Property<int>("HangHoaId")
                        .HasColumnType("int");

                    b.Property<int>("MaDonHangId")
                        .HasColumnType("int");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<byte>("GiamGia")
                        .HasColumnType("tinyint");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("HangHoaId", "MaDonHangId");

                    b.HasIndex("MaDonHangId");

                    b.ToTable("DonHangChiTiet");
                });

            modelBuilder.Entity("WebAPI_CodeFirst_bai1.Models.HangHoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<double>("GiamGia")
                        .HasColumnType("float");

                    b.Property<int?>("Loai")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHangHoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Loai");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("WebAPI_CodeFirst_bai1.Models.Loai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("WebAPI_CodeFirst_bai1.Models.DonHangChiTiet", b =>
                {
                    b.HasOne("WebAPI_CodeFirst_bai1.Models.HangHoa", "HangHoa")
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("HangHoaId")
                        .HasConstraintName("PK_DonHangChiTiet_HangHoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_CodeFirst_bai1.Models.DonHang", "DonHang")
                        .WithMany("DonHangChiTiet")
                        .HasForeignKey("MaDonHangId")
                        .HasConstraintName("PK_DonHangChiTiet_DonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("WebAPI_CodeFirst_bai1.Models.HangHoa", b =>
                {
                    b.HasOne("WebAPI_CodeFirst_bai1.Models.Loai", "loai")
                        .WithMany()
                        .HasForeignKey("Loai");

                    b.Navigation("loai");
                });

            modelBuilder.Entity("WebAPI_CodeFirst_bai1.Models.DonHang", b =>
                {
                    b.Navigation("DonHangChiTiet");
                });

            modelBuilder.Entity("WebAPI_CodeFirst_bai1.Models.HangHoa", b =>
                {
                    b.Navigation("DonHangChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
